apiVersion: v1
kind: Service
metadata:
  name: song-recommendation-chatbot-service
  labels:
    app: song-recommendation-chatbot
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: song-recommendation-chatbot